# admin/Dockerfile
# --- Stage 1: Build React App ---
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# --- Stage 2: Serve với Nginx ---
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

# Mở port 80 cho Nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]